---
- debug:
    var: item.source_archive

- name: Retrieve source archives
  get_url:
    url: "{{ item.source_url }}"
    dest: "/home/{{ data_user }}/{{ item.source_archive }}"
    owner: "{{ data_user }}"
    group: "{{ data_user }}"
  become: true

- name: Untar source archives
  unarchive:
    src: "/home/{{ data_user }}/{{ item.source_archive }}"
    dest: "/home/{{ data_user }}"
    remote_src: true
    owner: "{{ data_user }}"
    group: "{{ data_user }}"
  become: true

- name: Configure package build environment
  command: "./configure {{ item.configure_options|join(' ') }}"
  args:
    chdir: "/home/{{ data_user }}/{{ item.source_dir }}"
  become: true
  become_user: "{{ data_user }}"

- name: Build package
  command: make -j8
  args:
    chdir: "/home/{{ data_user }}/{{ item.source_dir }}"
  become: true
  become_user: "{{ data_user }}"

- name: Check build
  command: make -j8 check
  args:
    chdir: "/home/{{ data_user }}/{{ item.source_dir }}"
  become: true
  become_user: "{{ data_user }}"
  when: item.check

- name: Install
  command: make install
  args:
    chdir: "/home/{{ data_user }}/{{ item.source_dir }}"
  become: true
  notify: Rebuild library cache

- name: Flush all handlers
  meta: flush_handlers