---
- debug:
    var: item.source_archive

- name: Retrieve source archives
  get_url:
    url: "{{ item.source_url }}"
    dest: "/home/cloud-user/{{ item.source_archive }}"

- name: Untar source archives
  unarchive:
    src: "/home/cloud-user/{{ item.source_archive }}"
    dest: "/home/cloud-user"
    remote_src: true

- name: Configure package build environment
  command: "./configure {{ item.configure_options|join(' ') }}"
  args:
    chdir: "/home/cloud-user/{{ item.source_dir }}"

- name: Build package
  command: make -j8
  args:
    chdir: "/home/cloud-user/{{ item.source_dir }}"

- name: Check build
  command: make -j8 check
  args:
    chdir: "/home/cloud-user/{{ item.source_dir }}"
  when: item.check

- name: Install
  command: make install
  args:
    chdir: "/home/cloud-user/{{ item.source_dir }}"
  become: true
  notify: Rebuild library cache

- name: Flush all handlers
  meta: flush_handlers