---
- name: Create data directory
  file:
    path: "{{ data_dir }}"
    state: directory
    mode: "{{ data_mode }}"
    owner: "{{ data_user }}"
    group: "{{ data_user }}"
  become: true

- name: Retrieve files from Data Commons via lftp
  shell: "lftp -c 'open ftp://192.5.158.180; mget -O {{ data_dir }}/ /pub/commons/meteorology/pollard-melange-ice-sheet-model2018/*'"
  args:
    creates: "{{ data_dir }}/code"
  become: true

- name: Update data ownership
  shell: "chown -Rh {{ data_user }}:{{ data_user }} {{ data_dir }}"
  become: true

- name: Retrieve list of archives in data directory
  find:
    paths: "{{ data_dir }}"
    patterns: '*.zip,*.tgz,*.tbz,*.txz,*.tar.gz,*.tar.bz2,*.tar.xz'
  become: true
  register: archives

- name: Unzip data archives
  unarchive:
    src: "{{ item.path }}"
    dest: "{{ data_dir }}"
    remote_src: true
    owner: "{{ data_user }}"
    group: "{{ data_user }}"
  become: true
  loop: "{{ archives.files }}"

- name: Remove archives
  file:
    path: "{{ item.path }}"
    state: absent
  become: true
  loop: "{{ archives.files }}"