---
- name: Create data directory
  file:
    path: "{{ data_dir }}"
    state: directory
    mode: "{{ data_mode }}"
    owner: "{{ data_user }}"
    group: "{{ data_user }}"
  become: true

- name: Retrieve files from Data Commons via lftp
  shell: lftp -c 'open ftp://192.5.158.180; mget -O /DATA/ /pub/commons/meteorology/pollard-melange-ice-sheet-model2018/*'
  #shell: /usr/bin/lftp -c 'open ftp://192.5.158.180; mget -O /DATA/ /pub/commons/meteorology/pollard-melange-ice-sheet-model2018/*'

- name: Retrieve list of archives in data directory
  find:
    paths: "{{ data_dir }}"
    patterns: '*.zip,*.tgz,*.tbz,*.txz,*.tar.gz,*.tar.bz2,*.tar.xz'
  register: archives

- name: Unzip data archives
  unarchive:
    src: "{{ item.path }}"
    dest: "{{ data_dir }}"
    remote_src: true
  loop: "{{ archives.files }}"

- name: Remove archives
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ archives.files }}"