---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-version-specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

# - name: Upgrade system OS
#   yum:
#     name: '*'
#     state: latest
#   become: true
#   when:
#     - ansible_os_family == "RedHat"

- name: Install Software Stack
  include_tasks: install_swst.yml

- name: Clean up Yum cache
  shell: yum clean all
  become: true
  #warn: false
  when:
    - ansible_os_family == "RedHat"

- name: Get Ice Sheets Data
  include_tasks: get_data.yml
